from .auth import solve_challenge
from .client import EpCubeAsyncClient
from .const import BASE_URLS, USER_AGENT, DayType, Region, Scope, SystemStatus, WorkMode
from .exceptions import (
    EpCubeAPIError,
    EpCubeAuthError,
    EpCubeCaptchaError,
    EpCubeConnectionError,
    EpCubeError,
    EpCubeForbiddenError,
    EpCubeLoginError,
    EpCubeNotFoundError,
    EpCubeRateLimitError,
    EpCubeResponseError,
    EpCubeServerError,
    EpCubeTimeoutError,
)
from .models import (
    Account,
    DeviceDetail,
    DeviceSummary,
    EnergySeries,
    EnergyTotals,
    LiveSnapshot,
    ModeConfig,
    NetworkInfo,
    OutageEvent,
    PvString,
    PvStrings,
    SeriesPoint,
    SeriesReading,
    SwitchModeRequest,
    TouWindow,
    Warranty,
)
from .models.snapshot import Snapshot
from .registry import ROUTES, Route

__version__ = "0.3.0"

__all__ = [
    "BASE_URLS",
    "ROUTES",
    "USER_AGENT",
    "Account",
    "DayType",
    "DeviceDetail",
    "DeviceSummary",
    "EnergySeries",
    "EnergyTotals",
    "EpCubeAPIError",
    "EpCubeAsyncClient",
    "EpCubeAuthError",
    "EpCubeCaptchaError",
    "EpCubeConnectionError",
    "EpCubeError",
    "EpCubeForbiddenError",
    "EpCubeLoginError",
    "EpCubeNotFoundError",
    "EpCubeRateLimitError",
    "EpCubeResponseError",
    "EpCubeServerError",
    "EpCubeTimeoutError",
    "LiveSnapshot",
    "ModeConfig",
    "NetworkInfo",
    "OutageEvent",
    "PvString",
    "PvStrings",
    "Region",
    "Route",
    "Scope",
    "SeriesPoint",
    "SeriesReading",
    "Snapshot",
    "SwitchModeRequest",
    "SystemStatus",
    "TouWindow",
    "Warranty",
    "WorkMode",
    "__version__",
    "solve_challenge",
]
